name = "luoguchatserver"
main = "worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

account_id = "f408a22ce71832c99dab8f500445db1c"

[[kv_namespaces]]
binding = "chat_kv"
id = "f3aa6d93c686425ab409eacac1a54448"
preview_id = "f3aa6d93c686425ab409eacac1a54448"

[vars]
ENVIRONMENT = "production"

[observability]
enabled = true
